--Table: public.config_table

CREATE TABLE IF NOT EXISTS public.config_table
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    config_name character varying(255) COLLATE pg_catalog."default",
    config_value character varying(255) COLLATE pg_catalog."default",
    aspsp_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT config_table_pkey PRIMARY KEY (id),
    CONSTRAINT uk_86jfr9egnal08hml9uynud1kk UNIQUE (config_name, aspsp_id)
)
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

ALTER TABLE public.config_table OWNER to postgres;


-- Table: public.consent_table

CREATE TABLE IF NOT EXISTS public.consent_table
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    aspsp_id character varying(255) COLLATE pg_catalog."default",
    consent_expiration_date_time character varying(255) COLLATE pg_catalog."default",
    consent_id character varying(255) COLLATE pg_catalog."default",
    consent_status character varying(255) COLLATE pg_catalog."default",
    consent_status_update_date_time character varying(255) COLLATE pg_catalog."default",
    consent_transaction_from_date_time character varying(255) COLLATE pg_catalog."default",
    consent_transaction_to_date_time character varying(255) COLLATE pg_catalog."default",
    consent_type character varying(255) COLLATE pg_catalog."default",
    create_date_time timestamp without time zone,
    session_reference_id character varying(255) COLLATE pg_catalog."default",
    object_state character varying(1000) COLLATE pg_catalog."default",
    tracking_id character varying(255) COLLATE pg_catalog."default",
    update_date_time timestamp without time zone,
    CONSTRAINT consent_table_pkey PRIMARY KEY (id),
    CONSTRAINT uniqueconsentconstraint UNIQUE (tracking_id)
)
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

ALTER TABLE public.consent_table OWNER to postgres;


-- Table: public.consent_token_table

CREATE TABLE IF NOT EXISTS public.consent_token_table
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    access_token character varying(2000) COLLATE pg_catalog."default",
    create_date_time timestamp without time zone,
    expires_in bigint NOT NULL,
    resource_access_token character varying(2000) COLLATE pg_catalog."default",
    resource_refresh_token character varying(2000) COLLATE pg_catalog."default",
    token_expiration_date_time character varying(255) COLLATE pg_catalog."default",
    token_status character varying(255) COLLATE pg_catalog."default",
    update_date_time timestamp without time zone,
    consent_tid bigint,
    CONSTRAINT consent_token_table_pkey PRIMARY KEY (id),
    CONSTRAINT fk7c4cpl7s9gl7dkangqyyncey FOREIGN KEY (consent_tid)
        REFERENCES public.consent_table (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

ALTER TABLE public.consent_token_table OWNER to postgres;


-- Table: public.session_table

CREATE TABLE IF NOT EXISTS public.session_table
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    aspsp_id character varying(255) COLLATE pg_catalog."default",
    create_date_time timestamp without time zone,
    internal_access_token character varying(255) COLLATE pg_catalog."default",
    reference_id character varying(255) COLLATE pg_catalog."default",
    tid character varying(255) COLLATE pg_catalog."default",
    tpp_id character varying(255) COLLATE pg_catalog."default",
    update_date_time timestamp without time zone,
    user_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT session_table_pkey PRIMARY KEY (id),
    CONSTRAINT uniquesessionconstraint UNIQUE (tid, tpp_id)
)
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

ALTER TABLE public.session_table OWNER to postgres;