name: openbanking-paymentinitiation-ci

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ ubuntu-latest ] #[ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: paymentinitiation
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        env:
          MIGRATE_TEST_SCRIPT_URL:  file://scripts/postgresql
          MIGRATE_TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/paymentinitiation?sslmode=disable
          MIGRATE_VERSION: "2"
          DRIVER_NAME: postgres
          DATASOURCE_URL: postgres://postgres:postgres@localhost:5432/paymentinitiation?sslmode=disable
        run: |
          go run ./cmd/migrate
          ls -lt ./testdata/
          go test -v ./...
      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o payment ./cmd/payment
          CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o callback ./cmd/callback
          ls -lt
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: .
          repository: kaktas/openbanking-paymentinitiation
          tags: latest
